### ISSUE TITLE
new users in slack are ignored until re-start

### ISSUE THREAD

**Issue by geisslet** [sapcc/pulsar#2]
It seems there is no update of the slack user objects. 
If someone joins after start he stays unknown

**Comment by auhlig** [comment]
The [authorizer](https://github.com/sapcc/pulsar/blob/master/pkg/auth/authorizer.go) updates the  list of slack users based on the configured slack user groups every 10 minutes. 
I still see this happening in the logs and this seems to have worked in the past with user's being assigned/removed from the resp. slack user groups.
Do you have some details?

**Comment by geisslet** [comment]
New managed service member joined our slack workspace. 
Instance ran since >40 days - there was a error message in the log if he tried to ack (sorry - didn't copy it - from the code I think it was "cannot find slack user" - he was already a member of an authorized group //that was checked).
After restart problem was gone
From code it seems to be covered - I agree. 
Hard to reproduce though :(

**Comment by geisslet** [comment]
luckily same case happens due to new onboard:
`level=info ts=2020-06-15T07:46:59.399673392Z caller=core.go:140 component=api msg="rejecting unauthorized user" username=<sap_id> userid=<slack_id>`

**Comment by auhlig** [comment]
Can you confirm
1. User is part of a configured slack group granting the required role for the action
2. Action was triggered by user after sync (happens every 10min)

Possibly 2. didn't happen yet. 
There should be a [log line for the authorizer's sync](https://github.com/sapcc/pulsar/blob/master/pkg/auth/authorizer.go#L123) if being run in debug mode
